### PR TITLE
fix: handle parse errors

### LINKED ISSUE #13: Invalid RDF causes requests to stall
There is no error handling when reading the request body stream.

If parsing fails, the request never sends any response and no error is reissued either

### PR DESCRIPTION
**Pull request by tpluscode**
fixes #13

### CODE REVIEW

**Review by bergos — APPROVED** [review]

**Review by bergos — CHANGES_REQUESTED** [review]
Noticed an error in Travis. Can you check what's wrong?

File: index.js [hunk 1]
```diff
@@ -29,7 +29,15 @@ function readQuadStream ({ formats, mediaType, options, req, getBaseIri }) {
   Promise.resolve().then(async () => {
     const parserOptions = await buildOptions(req, options, getBaseIri)
 
-    formats.parsers.import(mediaType, req, parserOptions).pipe(passThrough)
+    const parserStream = formats.parsers.import(mediaType, req, parserOptions)
+    parserStream.on('error', parseError => {
+      passThrough.emit('error', httpError(400, parseError, {
+        statusCode: 400,
+        status: 'Bad Request',
```
Comment (bergos) [inline index.js:36]: `standard` complains about the trailing comma.

**Review by bergos — CHANGES_REQUESTED** [review]

**Review by bergos — APPROVED** [review]

**Comment by bergos** [comment]
released as 1.2.2
